@echo off
cd /d "C:\Users\Alkaeya De la Pena\Documents\bootcamp\boiler-plate-nextjs"

REM Remove setup documentation files
git rm -f "00_READ_ME_FIRST.md"
git rm -f "00_START_HERE.md"
git rm -f "BUILD_COMPLETE.md"
git rm -f "COMPLETE_SETUP_SUMMARY.md"
git rm -f "COMPONENTS_SETUP.md"
git rm -f "DELIVERY_REPORT.md"
git rm -f "DEPLOYMENT_GUIDE.md"
git rm -f "EXECUTION_GUIDE.md"
git rm -f "FINAL_SETUP_REPORT.md"
git rm -f "FINAL_SUMMARY.md"
git rm -f "IMPLEMENTATION_CHECKLIST.md"
git rm -f "INDEX.md"
git rm -f "MANIFEST.md"
git rm -f "MASTER_INDEX.md"
git rm -f "PROJECT_SETUP_SUMMARY.md"
git rm -f "PROJECT_SUMMARY.md"
git rm -f "QUICK_REFERENCE.md"
git rm -f "QUICK_START.md"
git rm -f "README_COMPONENTS.md"
git rm -f "README_NEW.md"
git rm -f "README_SETUP.md"
git rm -f "SETUP_COMPLETE.md"
git rm -f "SETUP_CV_WEBSITE.md"
git rm -f "SETUP_INSTRUCTIONS.md"
git rm -f "SETUP_READY.md"
git rm -f "START_HERE.md"
git rm -f "START_SETUP.md"

REM Remove setup scripts
git rm -f "complete-setup.js"
git rm -f "exec-move.bat"
git rm -f "fix-dev-server.bat"
git rm -f "move-components-windows.bat"
git rm -f "move-components.js"
git rm -f "move-files-now.js"
git rm -f "move-files-to-components.js"
git rm -f "move-to-components.js"
git rm -f "move_components.bat"
git rm -f "move_components.py"
git rm -f "move_files.bat"
git rm -f "movefiles.bat"
git rm -f "movefiles.js"
git rm -f "movefiles.py"
git rm -f "organize-components.js"
git rm -f "organize-files-final.js"
git rm -f "organize-files.js"
git rm -f "organize.bat"
git rm -f "organize.sh"
git rm -f "quick-setup.js"
git rm -f "run-complete-setup.bat"
git rm -f "run-organization.bat"
git rm -f "run-script.bat"
git rm -f "setup-components.bat"
git rm -f "setup-project.bat"
git rm -f "setup-structure.js"
git rm -f "setup.py"

REM Remove other unnecessary files
git rm -f "page-example.tsx"
git rm -f "remove-files.bat"

REM Commit the cleanup
git commit -m "refactor: remove setup files and documentation clutter"

echo Cleanup complete!
pause
